model:
  name: convnext_tiny
  pretrained: true

processor:
  name: convnextv2_huge_22k_384
  train:
    use_randaugment: true
    randaugment_n: 2
    randaugment_m: 9
    scale: [0.5, 1.0]
    ratio: [0.75, 1.33]
    hflip_prob: 0.5
    vflip_prob: 0.1
    rotation_degrees: 15
    use_color_jitter: true
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
    hue: 0.2
    grayscale_prob: 0.1
    blur_prob: 0.2
    blur_sigma: [0.1, 2.0]
    use_random_erasing: true
    erasing_prob: 0.25
    erasing_scale: [0.02, 0.33]
    erasing_ratio: [0.3, 3.3]