defaults:
  - dataset: flowers102
  - evaluation: default
  - _self_
model:
  name: microsoft/resnet-152
  pretrained: true
processor:
  name: microsoft/resnet-152
  train:
    use_different_processors: true
    use_randaugment: true
    randaugment_n: 2
    randaugment_m: 9
    scale: [0.5, 1.0]
    ratio: [0.75, 1.33]
    hflip_prob: 0.5
    vflip_prob: 0.1
    rotation_degrees: 15
    use_color_jitter: true
    brightness: 0.4
    contrast: 0.4
    saturation: 0.4
    hue: 0.2
    grayscale_prob: 0.1
    blur_prob: 0.2
    blur_sigma: [0.1, 2.0]
    use_random_erasing: true
    erasing_prob: 0.25
    erasing_scale: [0.02, 0.33]
    erasing_ratio: [0.3, 3.3]
trainer:
  train_batch_size: 128
  eval_batch_size: 512
  dataloader_num_workers: 64
  learning_rate: 1.0e-4
  optimizer:
    name: adamw
    weight_decay: 1.0e-5
  lr_scheduler:
    name: wsd
    num_warmup_rate: 0.05
    num_decay_steps: 100
  precision:
    param_type: float32
    reduction_type: float32
    output_type: float32
  reshard_after_forward: false
  transformer_cls_names_to_wrap: null
  num_steps: 1000
  eval_steps: 20
  save_steps: 1000
  save_total_limit: 1
  logging_steps: 1
  report_to: wandb
  grad_norm_clip: 1.0
  output_dir: outputs/resnet152-wsd-adamw
  resume_from_checkpoint: null
  wandb_project: sc4001
  wandb_entity: pufanyi
  wandb_run_name: resnet152-wsd-adamw
  wandb_run_id: null
  wandb_tags: []
